spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: replace-me
            clientSecret: replace-me
          google:
            clientId: replace-me
            clientSecret: replace-me         
# ...